### ISSUE TITLE
Two language

### ISSUE THREAD

**Issue by kronic** [abiliojr/fts5-snowball#1]
How can I use two languages?

**Comment by abiliojr** [comment]
Short answer first, right now you can't.

Long answer: I've been thinking about it too, since I find it very useful. So far I have 2 options, from easier to implement, to one that is harder both to implement and use, but I guess will give the best results.
1. Apply the stemmer in different languages, (with some sort of priority), and stop processing for the first one that modifies the word. That's pretty much what a tool like Sphinx Search does: http://sphinxsearch.com/docs/latest/conf-morphology.html (all the way down).
2. Be able to insert text in the tables while indicating the language, same thing for match. (not sure if this is possible, have to check FTS5 API).

Right now, I think I'll go implementing it way #1.

Any suggestions?

**Comment by kronic** [comment]
language detection library https://github.com/CLD2Owners/cld2

**Comment by abiliojr** [comment]
Thank you very much for the library link. It looks really useful for several projects. But due the fact that it's README says:

> ...CLD2 is not designed to do well on very short text...

And as the FTS5 works by passing single words at a time to the tokenizer, I went into implementing my initial approach (which I think will work perfect on languages as different as Russian and English) of running into a list of suggested languages, and trying them until one is able to tokenize. The order means priority, so if most of your text is in Russian, then you should put Russian first.

This is the way that a fully blown dedicated search tool like Sphinx Search work. Later on, if I find a way to hint the language in the query (and get access to that query), I'll definitely include the library you mentioned. For now, I hope you find the current state of the art good enough for your needs. Don't hesitate to further contact me.
